### ISSUE TITLE
Demo using todobackend

### ISSUE THREAD

**Issue by paul-hammant** [ebarlas/microhttp#1]
https://todobackend.com/ is a an initiative to show that a bunch of REST services can pass a known frontend test suite.

That test suite is a Jasmine suite and runs in the browser. There' a series of requests performed in order. GET, POST and others. It is very cool.  Can `microhttp` stand in the middle and delegate requests to one of the other backends, and still pass the test suite.  

Or maybe a native TodoBackend using `microhttp`. Easiest to fork one of the existing Java ones perhaps - and there's no DB requirement - a HashMap would do.

**Comment by ebarlas** [comment]
Hi Paul, thanks for mentioning that. I'll take a look. 

Somewhat relatedly, I'm currently working on a fork of the https://github.com/TechEmpower/FrameworkBenchmarks repo so that Microhttp will be included in future performance comparisons.

**Comment by paul-hammant** [comment]
TechEmpower/FrameworkBenchmarks proves speed/load

The Todobackend work proves versatility and crude compatibility with specs :)

**Comment by bowbahdoe** [comment]
@paul-hammant It is nowhere near done, but I did start making an implementation of the [httrealworld.how](https://www.realworld.how/) spec

https://github.com/bowbahdoe/microhttp-realworld

I need to take a break from it to recover mental battery, but if you are still interested this seems to serve the same thematic goal.

**Comment by bowbahdoe** [comment]
@paul-hammant I got a demo repo for this now, it just needs to be documented + cleaned up but all the tests are passing.

https://github.com/bowbahdoe/microhttp-todobackend
