### ISSUE TITLE
Discussion - style option rather than using new EventLoop directly/explicitly for usual expected use?

### ISSUE THREAD

**Issue by rbygrave** [ebarlas/microhttp#10]
So instead of having this style ...

```java
    public static void main(String[] args) throws IOException, InterruptedException {

        Options options = new Options()
                .withPort(8080)
                .withSocketTimeout(Duration.ofSeconds(60))
                .withReadBufferSize(1_024 * 64)
                .withMaxRequestSize(1_024 * 1_024);

  
        Handler handler = ...;

        EventLoop eventLoop = new EventLoop(options, new DisabledLogger(), handler);
        Thread eventLoopThread = new Thread(() -> {
            try {
                eventLoop.start();
            } catch (IOException e) {
                // thread terminates
            }
        });
        eventLoopThread.start();

       ...
        
        eventLoopThread.join();
    }

```

Have a `MicroHttp.Builder` where we `with` the optional config options, pass the mandatory params to a `start()` ... under the hood create the event loop etc.

Return a `MicroHttp` with a `stop()` method?

```java
    public static void main(String[] args) throws IOException, InterruptedException {

        Handler handler = ...;

        var microHttp = new MicroHttp.newBuilder()
                .withPort(8080)
                .withSocketTimeout(Duration.ofSeconds(60))
                .withReadBufferSize(1_024 * 64)
                .withMaxRequestSize(1_024 * 1_024)

               .withLogger(...)

               .start(handler);  // creates event loop, starts
  

       microHttp.stop();

    }

```

Just using "defaults" would be like:

```java
public static void main(String[] args) {

  Handler handler = ...;

  var microHttp = new MicroHttp
      .newBuilder()
      .start(handler);
  

    // programmatically stop ..
    microHttp.stop();

}

```

The thinking would be to make the "usual use" a little bit more obvious (in theory).

**Comment by ebarlas** [comment]
Thanks for the suggestions! I agree with your goal of reducing boilerplate. Again, just trying to find the right balance. 

`EventLoop` seems like the right unit of composition. I'd like to avoid making it thread-aware. Thread awareness could go into an `EventLoopTask` or `MicroHttp`.

Is that how you were envisioning `MicroHttp`? Or is that `EventLoop` renamed? I'm not exactly sure what that abstraction covers in your examples.

Also, we can reduce the noise in the first snippet by making `EventLoop.start()` emit a log event on `IOException` as follows. Then thread construction can be the one-liner in the README: `Thread thread = new Thread(eventLoop::start);`.

```public void start() {
    try {
        doStart();
    } catch (IOException e) {
        if (logger.enabled()) {
            logger.log(e, new LogEntry("event", "terminate"));
        }
    }
}```

**Comment by rbygrave** [comment]
Yes. I am happy to close this ticket for now. Maybe revisit later on but I think what I'm suggesting is more "opinionated" wrt threading etc and I can understand you wanting to leave that to the client etc.

> Thread awareness could go into an EventLoopTask or MicroHttp.

Yes. Add MicroHttp with some "thread awareness" / "threading model" in mind.

That is, IF (big if) you can see 2 or so "threading models" that apply 99% of the time then we could do something to make those more trivial to use/adopt (Add a MicroHttp to wrap EventLoop just to make it trivial to use for those cases).  For myself, I probably have a specific threading model in mind with Loom/Virtual threads in particular to execute the handler code. Ultimately I am looking to test that theory to see if that has "a wide sweet spot" performance wise plus is simple to use - but yes that is pretty opinionated and not what you want MicroHttp to be at least at the moment.

So yes, happy to close this.

**Comment by ebarlas** [comment]
Sounds good. I'll close this. We can circle back later.
