### ISSUE TITLE
GET Request leads to null body.

### ISSUE THREAD

**Issue by bowbahdoe** [ebarlas/microhttp#26]
Making this issue to track. Sending a request without a content-length and that isn't a chunked transfer will lead to a `Request` that has a null value for `.body()`

**Comment by kishoreravi24** [comment]
Hi @ebarlas, could you please assign this task to me? I'd love the opportunity to work on it.

**Comment by ebarlas** [comment]
Hi @kishoreravi24, thanks for offering to contribute! @bowbahdoe opened a PR with the fix alongside the issue, I was just slow to respond.

https://github.com/ebarlas/microhttp/pull/27

**Comment by kishoreravi24** [comment]
PR: https://github.com/ebarlas/microhttp/pull/28
