### ISSUE TITLE
Create tagged GitHub releases

### ISSUE THREAD

**Issue by beatngu13** [ebarlas/microhttp#7]
There are currently two releases of Microhttp on Maven Central:

https://search.maven.org/artifact/org.microhttp/microhttp

[v0.1](https://github.com/ebarlas/microhttp/commit/e29fe8b47557ad199c804cff6982349a8285e482) and [v0.2](https://github.com/ebarlas/microhttp/commit/c35c2c41f5d96ddd8c36faf6038409a0690712c0) appear to have no corresponding Git tags:

https://github.com/ebarlas/microhttp/tags

There are also no GitHub releases:

https://github.com/ebarlas/microhttp/releases

Here are some release examples from a personal project:

https://github.com/beatngu13/pdf-zoom-wizard/releases

PR #6 will add a basic GitHub Actions build. Based on this, another workflow could be created to automatically set the project's version, tag the commit, and create a GitHub release. It is also possible to use something like [JReleaser](https://jreleaser.org).

What do you think? I'm happy to help if you are interested.

**Comment by ebarlas** [comment]
Thanks for raising this question. I thought it might go unnoticed. 

I'll give this some thought and circle back a bit later. And thank you for offering to help!

**Comment by ebarlas** [comment]
I added tags and releases for v0.1, v0.2, and v0.3.

**Comment by ebarlas** [comment]
Closing this for now. I'm content for the moment with my manual process for tags and releases. We can circle back later if needed.
